### PR TITLE
Version 0.18.0

### PR DESCRIPTION
**Pull request by bandersen23**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bandersen23** [comment]
@conda-forge-admin, please lint

**Comment by bandersen23** [comment]
@conda-forge-admin, please rerender

**Comment by bandersen23** [comment]
This is for #19.

**Comment by bandersen23** [comment]
@hadim This adds a patch to remove `mkdocstrings-python-legacy` from the dependencies for now so `pip check` passes. Once this is merged and built, you can rebuild your staged-recipes. Then I'll follow up on updating this one again.

**Comment by hadim** [comment]
Good to me. I'll let you merge.

Can you take care of the stage-recpies PR?

**Comment by bandersen23** [comment]
I can take a look at those recipes later today. I'll merge this PR when I get closer to having those merged.

**Pull request merged**
